//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ИП_Хевеши.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arrivals
    {
        public int ID { get; set; }
        public Nullable<int> ComponentID { get; set; }
        public System.DateTime ArrivalDate { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ProviderID { get; set; }
        public Nullable<int> ReceiptID { get; set; }
    
        public virtual Components Components { get; set; }
        public virtual Users Users { get; set; }
        public virtual Providers Providers { get; set; }
        public virtual Receipts Receipts { get; set; }
    }
}
