//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ИП_Хевеши.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ИП_ХевешиEntities : DbContext
    {
        public ИП_ХевешиEntities()
            : base("name=ИП_ХевешиEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Arrivals> Arrivals { get; set; }
        public virtual DbSet<Buyers> Buyers { get; set; }
        public virtual DbSet<Components> Components { get; set; }
        public virtual DbSet<InventoryChecks> InventoryChecks { get; set; }
        public virtual DbSet<Issuance> Issuance { get; set; }
        public virtual DbSet<Manufacturers> Manufacturers { get; set; }
        public virtual DbSet<Movements> Movements { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Zones> Zones { get; set; }
        public virtual DbSet<Providers> Providers { get; set; }
        public virtual DbSet<Receipts> Receipts { get; set; }
        public virtual DbSet<IssuanceReceipts> IssuanceReceipts { get; set; }
    }
}
