//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ИП_Хевеши.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryChecks
    {
        public int ID { get; set; }
        public Nullable<int> ComponentID { get; set; }
        public Nullable<System.DateTime> InventoryDate { get; set; }
        public Nullable<int> ActualQuantity { get; set; }
    
        public virtual Components Components { get; set; }
    }
}
