//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ИП_Хевеши.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssuanceReceipts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IssuanceReceipts()
        {
            this.Issuance = new HashSet<Issuance>();
        }
    
        public int ID { get; set; }
        public string ReceiptNumber { get; set; }
        public System.DateTime Date { get; set; }
        public int BuyerID { get; set; }
        public int UserID { get; set; }
    
        public virtual Buyers Buyers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Issuance> Issuance { get; set; }
        public virtual Users Users { get; set; }
    }
}
