//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ИП_Хевеши.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movements
    {
        public int ID { get; set; }
        public Nullable<int> ComponentID { get; set; }
        public Nullable<System.DateTime> MovementDate { get; set; }
        public string FromZone { get; set; }
        public string ToZone { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Components Components { get; set; }
    }
}
