//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ИП_Хевеши.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Receipts()
        {
            this.Arrivals = new HashSet<Arrivals>();
        }
    
        public int ID { get; set; }
        public string ReceiptNumber { get; set; }
        public System.DateTime Date { get; set; }
        public int ProviderID { get; set; }
        public int UserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Arrivals> Arrivals { get; set; }
        public virtual Providers Providers { get; set; }
        public virtual Users Users { get; set; }
    }
}
